### ISSUE TITLE
Add Pokémon information

### ISSUE THREAD

**Issue by luissmg** [luissmg/rotom-dexter#5]
### Tasks
- [x] Add weight, height and type
- [ ] Add base attack, defense and stamina
- [ ] Add Pokédex entry and number
- [ ] Add gender information
- [ ] Add buddy distance and size
- [ ] Add evolutions
- [ ] Add attack probability, capture rate and flee rate
